name: Pipeline_PullRequests

on:
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create docker containers
      run: | 
        cd src/
        docker-compose up -d
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Dotnet Build
      run: dotnet build --configuration Release ./src/SolutionTemplate.sln

    - name: Dotnet Test
      run: |
        sudo bash ./.github/workflows/WaitForDatabase.sh -h localhost -p 3306 -t 60
        dotnet test --configuration Release ./src/SolutionTemplate.sln
