name: Pipeline_PullRequests

on:
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Dotnet Build
      run: dotnet build --configuration Release ./src/SolutionTemplate.sln

    - name: Dotnet Test
      run: dotnet test --configuration Release ./src/test/TestUnitarios/TestUnitarios.csproj

    - name: Run test with Docker compose
      run: | 
        cd ./.github/workflows
        docker-compose up -d
    # - name: Dotnet Test
    #   run: |
    #     ./.github/workflows/WaitForDatabase.sh localhost:3306
    #     dotnet test --configuration Release ./src/SolutionTemplate.sln
