name: Pipeline_PullRequests

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        ports:
        - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: 123456
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Building dotnet
      run: dotnet build --configuration Release ./src/SolutionTemplate.sln

    - name: Init Database
      run: |
        echo 'Iniciando sesion'
        sudo systemctl start mysql
        mysql -uroot -p123456 < ./src/.docker/MySqlDatabaseInit/initMysql.sql

    - name: Testing dotnet
      run: |
        dotnet test --configuration Release ./src/SolutionTemplate.sln
