version: '3.8'

services:
  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    # volumes:
    #   - .:/src
    #   - ../test:/test
    working_dir: /src
    command:
      [
        "dotnet",
        "test",
        "src/SolutionTemplate.sln"
      ]
    depends_on:
      - database
      - logger

  database:
    extends:
      file: ../../src/docker-compose.yml
      service: mysql

  logger:
    extends:
      file: ../../src/docker-compose.yml
      service: graylog